import{a as S,S as P,i as l}from"./assets/vendor-D8_O3--j.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const v="50984165-ff91babc2717b2b8abbd0ea6f",q="https://pixabay.com/api/";async function p(r,o=1,s=15){const i={key:v,q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",page:o,per_page:s};return(await S.get(q,{params:i})).data}function m(r){return r.map(({webformatURL:o,largeImageURL:s,tags:i,likes:e,views:t,comments:a,downloads:w})=>`
        <li class="gallery-item">
          <a href="${s}">
            <img src="${o}" alt="${i}" loading="lazy" />
          </a>
          <div class="info">
            <p><b>Likes:</b> ${e}</p>
            <p><b>Views:</b> ${t}</p>
            <p><b>Comments:</b> ${a}</p>
            <p><b>Downloads:</b> ${w}</p>
          </div>
        </li>
      `).join("")}function E(){const r=document.querySelector(".gallery");r.innerHTML=""}const R=document.querySelector(".form"),d=document.querySelector(".gallery"),g=document.querySelector(".loader"),n=document.createElement("button");n.textContent="Load more";n.classList.add("load-more");n.style.display="none";d.after(n);const h=new P(".gallery a");let c=1,y="";const u=15;let f=0;R.addEventListener("submit",$);n.addEventListener("click",H);async function $(r){r.preventDefault();const o=r.currentTarget.elements.searchQuery.value.trim();if(!o){l.warning({message:"Please enter a search query.",position:"topRight"});return}y=o,c=1,E(),n.style.display="none",b();try{const s=await p(y,c,u);if(f=s.totalHits,s.hits.length===0){l.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}d.insertAdjacentHTML("beforeend",m(s.hits)),h.refresh(),f>u?n.style.display="block":n.style.display="none"}catch{l.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{L()}}async function H(){c++,b(),n.style.display="none";try{const r=await p(y,c,u);d.insertAdjacentHTML("beforeend",m(r.hits)),h.refresh();const{height:o}=d.firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"}),c*u>=f?(n.style.display="none",l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):n.style.display="block"}catch{l.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{L()}}function b(){g.classList.remove("hidden")}function L(){g.classList.add("hidden")}
//# sourceMappingURL=index.js.map
